project:
  type: website

execute:
  freeze: auto

website:
  title: "Geospatial small area estimation - A how-to guide"
  favicon: docs/images/favicon.drawio.svg
  repo-url: https://github.com/ESCAP-SD/geospatialSAEhowto
  issue-url: https://github.com/ESCAP-SD/geospatialSAEhowto/issues/new
  repo-actions: [issue, source]
  bread-crumbs: true
  page-navigation: true
  back-to-top-navigation: true
  search: true
  sidebar:
    style: "docked"
    type: "dark"
    search: true
    logo: assets/image.png
    logo-alt: logo
    logo-href: https://escap-sd.github.io/geospatialSAEhowto/docs/
    border: true
    tools:
      - icon: github
        href: https://github.com/ESCAP-SD/geospatialSAEhowto
        text: GitHub account for this training
      # - icon: globe
      #   href: https://xtophe.notion.site/Web-Scraping-for-CPI-Training-c36b27c2ea6b4f02ad760069afaf6fb5
      #   text: "Notion site: home page for the overall web scraping training"
    contents:
      - href: docs/index.qmd
        text: Introduction
      - section: 
        href: docs/chapter1.qmd
        contents: 
          - docs/chapter1-1.qmd
          - docs/chapter1-2.qmd
      - section:
      - href: docs/chapter2.qmd
        contents:
          - docs/chapter2-1.qmd
          - docs/chapter2-2.qmd
  page-footer: 
    left: "2025, ESCAP"

format:
  html:
    theme: 
      light: cosmo
      dark: darkly
    css: docs/styles.css
    toc: true
    grid:
      sidebar-width: 350px
      body-width: 900px
      margin-width: 300px